/*Fichero script para comprobar las restricciones de integridad existentes sobre las tablas*/
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS
WHERE TABLE_NAME= 'CIUDAD' OR TABLE_NAME= 'USUARIO' OR TABLE_NAME= 'TIPO_DATO_BANCARIO' 
OR TABLE_NAME= 'DATO_BANCARIO' OR TABLE_NAME= 'PUESTO' OR TABLE_NAME= 'ESTADO_PEDIDO' 
OR TABLE_NAME= 'CODIGO_POSTAL ' OR TABLE_NAME= 'DIRECCION' OR TABLE_NAME= 'MODELO' 
OR TABLE_NAME= 'CENTRO_DE_OPERACIONES ' OR TABLE_NAME= 'ALMACEN' OR TABLE_NAME= 'OFICINA' 
OR TABLE_NAME= 'EMPLEADO' OR TABLE_NAME= 'PEDIDO' OR TABLE_NAME= 'PRODUCTO' 
OR TABLE_NAME= 'RECLAMACION_QUEJA' OR TABLE_NAME= 'DISPONIBILIDAD' 
OR TABLE_NAME= 'DOMICILIO_EMPLEADO' OR TABLE_NAME= 'DOMICILIO_USUARIO' OR TABLE_NAME= 'CONTIENE' ;
