/*FICHERO PARA COMPROBAR QUE ESTÁN TODOS LOS DATOS INSERTADOS*/

SELECT * FROM CIUDAD;

SELECT * FROM USUARIO;

SELECT * FROM TIPO_DATO_BANCARIO;

SELECT * FROM DATO_BANCARIO;

SELECT * FROM PUESTO;

SELECT * FROM ESTADO_PEDIDO;

SELECT * FROM CODIGO_POSTAL;

SELECT * FROM DIRECCION;

SELECT * FROM MODELO;

SELECT * FROM CENTRO_DE_OPERACIONES;

SELECT * FROM ALMACEN;

SELECT * FROM OFICINA;

SELECT * FROM EMPLEADO;

SELECT * FROM PEDIDO;

SELECT * FROM PRODUCTO;

SELECT * FROM RECLAMACION_QUEJA;

SELECT * FROM DISPONIBILIDAD;

SELECT * FROM DOMICILIO_EMPLEADO;

SELECT * FROM DOMICILIO_USUARIO;