/*FICHERO PARA CREACIÓN DE BASE DE DATOS*/

/*BIEN*/
CREATE TABLE CIUDAD (
ID NUMBER(5) CONSTRAINT CIU_ID_NN NOT NULL CONSTRAINT CIU_ID_PK PRIMARY KEY,
NOMBRE VARCHAR(30) CONSTRAINT CIU_NOM_NN NOT NULL CONSTRAINT CIU_NOM_UN UNIQUE
);

/*FALTA AÑADIR LA DIRECCIÓN QUE DEBERÍA SER DE N A N*/
CREATE TABLE USUARIO(
DNI VARCHAR(9) CONSTRAINT US_DNI_NN NOT NULL CONSTRAINT US_DNI_PK PRIMARY KEY,
NOMBRE VARCHAR(25) CONSTRAINT US_NOM_NN NOT NULL CONSTRAINT US_NOM_UN UNIQUE,
APELLIDO VARCHAR(40) CONSTRAINT US_APE_NN NOT NULL CONSTRAINT US_APE_UN UNIQUE,
EMAIL VARCHAR(60) CONSTRAINT US_EM_NN NOT NULL CONSTRAINT US_EM_UN UNIQUE,
CONTRA VARCHAR(32) CONSTRAINT US_CNTR_NN NOT NULL,
FECHA_NACIMIENTO DATE CONSTRAINT US_FCHA_NAC_NN NOT NULL
);

/*BIEN*/
CREATE TABLE TIPO_DATO_BANCARIO(
ID NUMBER(2) CONSTRAINT T_DT_BN_ID_NN NOT NULL CONSTRAINT T_DT_BN_ID_PK PRIMARY KEY,
DENOMINACION VARCHAR (25) CONSTRAINT T_DT_BN_DEN_NN NOT NULL CONSTRAINT T_DT_BN_DEN_UN UNIQUE
);

CREATE TABLE DATO_BANCARIO(
NUM VARCHAR(70) CONSTRAINT DT_BN_NUM_NN NOT NULL CONSTRAINT DAT_BAN_NUM_PK PRIMARY KEY ON DELETE CASCADE,
CVV NUMBER(3),
ID_TIPO_DATO_BANCARIO NUMBER(2) CONSTRAINT ID_T_DT_BN_NN NOT NULL CONSTRAINT DT_ID_T_DT_BN_FK REFERENCES TIPO_DATO_BANCARIO(ID) ON DELETE CASCADE,
USUARIO_DNI VARCHAR(9) CONSTRAINT DT_BN_US_DNI_NN NOT NULL CONSTRAINT DT_BN_US_DNI_FK REFERENCES USUARIO(DNI) ON DELETE CASCADE
);

/*BIEN*/
CREATE TABLE PUESTO(
ID NUMBER(4) CONSTRAINT PUESTO_ID_NN NOT NULL CONSTRAINT PUESTO_ID_PK PRIMARY KEY,
DENOMINACION VARCHAR(30) CONSTRAINT PUESTO_DENOM_NN NOT NULL CONSTRAINT PUESTO_DENOM_UN UNIQUE
);

/*BIEN*/
CREATE TABLE ESTADO_PEDIDO(
ID NUMBER(2) CONSTRAINT ET_PED_ID_NN NOT NULL CONSTRAINT ET_PED_ID_PK PRIMARY KEY,
DENOMINACION VARCHAR(20) ET_PED_DENOM_NN NOT NULL CONSTRAINT ET_PED_DENOM_UN UNIQUE
);

/*BIEN*/
CREATE TABLE CODIGO_POSTAL(
CODIGO NUMBER(7) CONSTRAINT COD_PS_NN NOT NULL CONSTRAINT COD_PS_PK PRIMARY KEY,
CIUDAD_ID NUMBER(5) CONSTRAINT COD_PS_CIU_ID_NN NOT NULL CONSTRAINT COD_PS_CIU_ID_FK REFERENCES CIUDAD(ID) ON DELETE CASCADE
);


/*BIEN*/
CREATE TABLE DIRECCION(
ID NUMBER(9) CONSTRAINT DIR_ID_NN NOT NULL CONSTRAINT DIR_ID_PK PRIMARY KEY,
DIR VARCHAR(40) CONSTRAINT DIR_DIR_NN NOT NULL CONSTRAINT DIR_DIR_UN UNIQUE,
ID_CIUDAD NUMBER(5) CONSTRAINT DIR_CIU_ID_NN NOT NULL CONSTRAINT DIR_CIU_ID_FK REFERENCES CIUDAD(ID) ON DELETE CASCADE,
CODIGO_POSTAL NUMBER(7) CONSTRAINT DIR_COD_PS_NN NOT NULL CONSTRAINT DIR_COD_PS_FK REFERENCES CODIGO_POSTAL(CODIGO) ON DELETE CASCADE
);


CREATE TABLE MODELO(
ID NUMBER (9) CONSTRAINT MOD_ID_NN NOT NULL CONSTRAINT MODELO_ID_PK PRIMARY KEY,
NOMBRE VARCHAR(25) CONSTRAINT MOD_NOM_NN NOT NULL CONSTRAINT MOD_NOM_UN UNIQUE
);


CREATE TABLE CENTRO_DE_OPERACIONES(
ID NUMBER(9) CONSTRAINT CTR_OPE_ID_NN NOT NULL CONSTRAINT CTR_OPE_ID_PK PRIMARY KEY,
DENOMINACION VARCHAR(20) CONSTRAINT CTR_OPE_DENOM_NN NOT NULL
);


/**/
CREATE TABLE ALMACEN(
ID NUMBER(9) CONSTRAINT AM_ID_NN NOT NULL CONSTRAINT AM_ID_PK PRIMARY KEY,
DENOMINACION VARCHAR(20) CONSTRAINT AM_DENOM_NN NOT NULL,
ID_CENTRO_OPERACIONES NUMBER(9) CONSTRAINT ALMA_ID_C_OPS_NN NOT NULL CONSTRAINT AM_ID_CTR_OPS_FK REFERENCES CENTRO_DE_OPERACIONES(ID) ON DELETE CASCADE);

CREATE TABLE OFICINA(
ID NUMBER(9) CONSTRAINT OF_ID_NN NOT NULL CONSTRAINT OF_ID_PK PRIMARY KEY,
DENOMINACION VARCHAR(20) CONSTRAINT OF_DENOM_NN NOT NULL,
ID_CENTRO_OPERACIONES NUMBER(9) CONSTRAINT OF_ID_CTR_OPS_NN NOT NULL CONSTRAINT OF_ID_CTR_OPS_FK REFERENCES CENTRO_DE_OPERACIONES(ID) ON DELETE CASCADE
);


/**/
CREATE TABLE EMPLEADO(
DNI VARCHAR(9) CONSTRAINT EMP_DNI_NN NOT NULL CONSTRAINT EMP_DNI_PK PRIMARY KEY, 
NOMBRE VARCHAR(20) CONSTRAINT EMP_NOM_NN NOT NULL,
APELLIDOS VARCHAR (40) CONSTRAINT EMP_APE_NN NOT NULL,
FECHA_NACIMIENTO DATE CONSTRAINT EMP_FCH_NAC_NN NOT NULL,
EMAIL VARCHAR(25) CONSTRAINT EMP_EM_NN NOT NULL,
NSS NUMBER(12) CONSTRAINT EMP_NSS_NN NOT NULL,
ID_PUESTO NUMBER(4) CONSTRAINT EMP_ID_PST_NN NOT NULL CONSTRAINT EMP_ID_PST_FK REFERENCES PUESTO(ID) ON DELETE CASCADE,
ID_OFICINA NUMBER(9) CONSTRAINT EMP_ID_OFI_NN NOT NULL CONSTRAINT EMP_ID_OFI_FK REFERENCES OFICINA(ID)ON DELETE CASCADE,
ID_ALMACEN NUMBER(9) CONSTRAINT EMP_ID_AM_NN NOT NULL CONSTRAINT EMP_ID_AM_FK REFERENCES ALMACEN(ID)ON DELETE CASCADE,
ID_DIRECCION NUMBER(9) CONSTRAINT EMP_ID_DIR_NN NOT NULL CONSTRAINT EMP_ID_DIR_FK REFERENCES DIRECCION(ID)ON DELETE CASCADE,
DNI_JEFE VARCHAR(9) CONSTRAINT DNI_JEFE_NN NOT NULL CONSTRAINT EMP_DNI_JEFE_FK REFERENCES EMPLEADO(DNI) ON DELETE CASCADE 
);

/**/
CREATE TABLE PEDIDO(
ID NUMBER(15) CONSTRAINT PED_ID_NN NOT NULL CONSTRAINT PED_ID_PK PRIMARY KEY,
DESCRIPCION VARCHAR(100),
FECHA_PEDIDO DATE CONSTRAINT PED_FCHA_NN NOT NULL,
ID_ESTADO_PEDIDO NUMBER(2) CONSTRAINT PED_ET_PED_NN NOT NULL CONSTRAINT PED_ET_PED_ID_FK REFERENCES ESTADO_PEDIDO(ID),
NUM_DATO_BANCARIO VARCHAR(70) CONSTRAINT PED_NUM_DT_BAN_NN NOT NULL CONSTRAINT PED_NUM_DT_BAN_FK REFERENCES DATO_BANCARIO(NUM)ON DELETE CASCADE,
DNI_EMPLEADO VARCHAR(9) CONSTRAINT PED_DNI_EMP_NN NOT NULL CONSTRAINT PED_DNI_EMP_FK REFERENCES EMPLEADO(DNI)ON DELETE CASCADE,
DNI_USUARIO VARCHAR(9) CONSTRAINT PED_DNI_US_NN NOT NULL CONSTRAINT PED_DNI_US_FK REFERENCES USUARIO(DNI)ON DELETE CASCADE,
ID_DIRECCION NUMBER(9) CONSTRAINT PED_DIR_ID_NN NOT NULL CONSTRAINT PED_DIR_ID_FK REFERENCES DIRECCION(ID) ON DELETE CASCADE
);

/**/
CREATE TABLE PRODUCTO(
ID NUMBER (9) CONSTRAINT PRO_ID_NN NOT NULL CONSTRAINT PRO_ID_PK PRIMARY KEY,
DESCRIPCION VARCHAR(45) CONSTRAINT PRO_DESC_NN NOT NULL,
NOMBRE VARCHAR(25) CONSTRAINT PRO_NOM_NN NOT NULL CONSTRAINT PRO_NOM_UN UNIQUE,
PRECIO NUMBER (6) CONSTRAINT PRO_PRE_NN NOT NULL,
ID_MODELO NUMBER(9)  CONSTRAINT PRO_MOD_ID_NN NOT NULL CONSTRAINT PRO_MOD_ID_FK REFERENCES MODELO(ID) ON DELETE CASCADE
);

/*PRODUCTO Y PEDIDO*/

/**/
CREATE TABLE RECLAMACION_QUEJA( 
ID NUMBER(9) CONSTRAINT RC_QJ_ID_NN NOT NULL CONSTRAINT RC_QJ_ID_PK PRIMARY KEY,
DENOMINACION  VARCHAR(20) CONSTRAINT RC_QJ_DENOM_NN NOT NULL,
NUM_RECLAMACION NUMBER (9) CONSTRAINT RC_QJ_NUM_REC_NN CONSTRAINT RC_QJ_NUM_REC_UN UNIQUE,
DESCRIPCION VARCHAR(25) CONSTRAINT RC_QJ_DESC_NN NOT NULL,
ID_PEDIDO NUMBER(15) CONSTRAINT RC_QJ_ID_PED_NN NOT NULL CONSTRAINT RC_QJ_ID_PED_FK REFERENCES PEDIDO(ID) ON DELETE CASCADE,
DNI_EMPLEADO VARCHAR(9) CONSTRAINT RC_QJ_DNI_EMP_NN NOT NULL CONSTRAINT RECQJ_DNIEMP_FK REFERENCES EMPLEADO(DNI) ON DELETE CASCADE
);

/*REVISAR*/
CREATE TABLE DISPONIBILIDAD(
ID_MODELO NUMBER(9) CONSTRAINT DIS_ID_MOD_NN NOT NULL CONSTRAINT DISP_ID_MOD_FK REFERENCES MODELO(ID) ON DELETE CASCADE,
ID_ALMACEN NUMBER(9) CONSTRAINT DIS_ID_AM_NN NOT NULL CONSTRAINT DISP_ID_AM_FK REFERENCES ALMACEN(ID) ON DELETE CASCADE,
CANTIDAD NUMBER(9) CONSTRAINT DIS_CANT_O_PDF DEFAULT 0,
PRIMARY KEY ( ID_MODELO, ID_ALMACEN )
);

/*REVISAR*/
CREATE TABLE DOMICILIO_EMPLEADO(
ID_DIRECCION NUMBER(9) CONSTRAINT DM_EMP_NN NOT NULL CONSTRAINT DM_EMP_IDDIR_FK REFERENCES DIRECCION(ID) ON DELETE CASCADE,
DNI_EMPLEADO VARCHAR(9) CONSTRAINT DM_EMP_DNI_EMP_NN NOT NULL CONSTRAINT DM_EMP_DNIEMP_FK REFERENCES EMPLEADO(DNI) ON DELETE CASCADE,
PRIMARY KEY ( ID_DIRECCION, DNI_EMPLEADO )
);

/*REVISAR*/
CREATE TABLE DOMICILIO_USUARIO(
DNI_USUARIO VARCHAR(9) CONSTRAINT DM_US_DNI_NN NOT NULL CONSTRAINT DM_US_DNI_US_FK REFERENCES USUARIO(DNI) ON DELETE CASCADE,
ID_DIRECCION NUMBER(9) CONSTRAINT DM_US_ID_DIR_NN NOT NULL CONSTRAINT DM_US_ID_DIR_FK REFERENCES DIRECCION(ID) ON DELETE CASCADE,
PRIMARY KEY(DNI_USUARIO,ID_DIRECCION)

);


