CREATE TABLE CIUDAD (
ID NUMBER(4) CONSTRAINT CIUDAD_ID_NONULA NOT NULL CONSTRAINT CIUDAD_ID_PK PRIMARY KEY,
NOMBRE VARCHAR(30) CONSTRAINT CIUDAD_NOMBRE_NONULA NOT NULL CONSTRAINT CIUDAD_NOMBRE_UNICO UNIQUE
);

CREATE TABLE USUARIO(
DNI VARCHAR(9) CONSTRAINT USUARIO_DNI_NONULO NOT NULL CONSTRAINT USUARIO_DNI_PK PRIMARY KEY,
NOMBRE VARCHAR(25) CONSTRAINT USUARIO_NOMBRE_NONULO NOT NULL CONSTRAINT USUARIO_NOMBRE_UNICO UNIQUE,
APELLIDOS VARCHAR(40) CONSTRAINT USUARIONAPELLIDONONULO NOT NULL CONSTRAINT USUARIOAPELLIDOUNICO UNIQUE,
EMAIL VARCHAR() CONSTRAINT USUARIO_EMAIL_NONULO NOT NULL CONSTRAINT USUARIO_EMAIL_UNICO UNIQUE,
CONTRA VARCHAR(32) CONSTRAINT USUARIO_CONTRA_NONULO NOT NULL,
FECHA_NACIMIENTO DATE CONSTRAINT USUARIO_FECHA_NACIMIENTO_NONULO NOT NULL
);

