/*SCRIPT PARA LIMPIAR LA BASE DE DATOS*/

/*FIXME*/
/*
SET FEEDBACK OFF;
SET PAGESIZE 0;
SPOOL DROPOBJECTS.SQL;
SELECT 'DROP VIEW '||VIEW_NAME||';' FROM USER_VIEWS;
SELECT 'DROP INDEX '||INDEX_NAME||';' FROM USER_INDEXES;
SELECT DISTINCT 'DROP SEQUENCE '||SEQUENCE_NAME|| ';'FROM USER_SEQUENCES;
SELECT DISTINCT 'DROP TABLE '||TABLE_NAME|| ';'FROM USER_TABLES;
SELECT DISTINCT 'DROP PROCEDURE '||NAME|| ';'FROM USER_SOURCE WHERE TYPE = 'PROCEDURE';
SELECT DISTINCT 'DROP FUNCTION '||NAME|| ';'FROM USER_SOURCE WHERE TYPE = 'FUNCTION';
SELECT DISTINCT 'DROP PACKAGE '||NAME|| ';'FROM USER_SOURCE WHERE TYPE = 'PACKAGE';
SELECT DISTINCT 'DROP TYPE '||NAME|| ';'FROM USER_SOURCE WHERE TYPE = 'TYPE';
SELECT DISTINCT 'DROP TRIGGER '||NAME|| ';'FROM USER_SOURCE WHERE TYPE = 'TRIGGER';
SELECT 'DROP SYNONYM '||SYNONYM_NAME||';' FROM USER_SYNONYMS;
SPOOL OFF;
@ DROPOBJECTS.SQL;
*/

/*OPCION B*/
DROP TABLE CONTIENE;

DROP TABLE DOMICILIO_USUARIO;

DROP TABLE DOMICILIO_EMPLEADO;

DROP TABLE DISPONIBILIDAD;

DROP TABLE RECLAMACION_QUEJA;

DROP TABLE PRODUCTO;

DROP TABLE PEDIDO;

DROP TABLE EMPLEADO;

DROP TABLE OFICINA;

DROP TABLE ALMACEN;

DROP TABLE CENTRO_DE_OPERACIONES;

DROP TABLE MODELO;

DROP TABLE DIRECCION;

DROP TABLE CODIGO_POSTAL;

DROP TABLE ESTADO_PEDIDO;

DROP TABLE PUESTO;

DROP TABLE DATO_BANCARIO;

DROP TABLE TIPO_DATO_BANCARIO;

DROP TABLE USUARIO;

DROP TABLE CIUDAD;